### ISSUE TITLE
Letterboxing Not Working

### ISSUE THREAD

**Issue by sProgg** [Lanrutcon/CatchTheWind#1]
Here's the bug code:

3x CatchTheWind\CatchTheWind-1.0.lua:165: attempt to index field 'acceptButton' (a nil value)
CatchTheWind\CatchTheWind-1.0.lua:165: in function <CatchTheWind\CatchTheWind.lua:164>
CatchTheWind\CatchTheWind-1.0.lua:382: in function `?'
CatchTheWind\CatchTheWind-1.0.lua:441: in function <CatchTheWind\CatchTheWind.lua:439>

Locals:
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'acceptButton' (a nil value)"
letterBox = CatchTheWind {
 0 = <userdata>
 bottomPanel = <unnamed> {
 }
 isChatBubble = false
 topPanel = <unnamed> {
 }
 text = "I've found them, dwarf.  The Scourge.  How I've longed for this day."
 questText = <unnamed> {
 }
 rewardPanel = CTWrewardPanel {
 }
}
splitText = <function> defined @CatchTheWind\CatchTheWind.lua:54
animateText = <function> defined @CatchTheWind\CatchTheWind.lua:102

**Comment by Lanrutcon** [comment]
Hello and thanks for reporting.

This should be fixed by now. Download the most recent stable version in [Curse.com](https://mods.curse.com/addons/wow/catchthewind).

Commit: https://github.com/Lanrutcon/CatchTheWind/commit/ffe2f070316d906be2aed6eb1a385f32b23394c4
