### ISSUE TITLE
Russian Fonts bug

### ISSUE THREAD

**Issue by JaDenis** [Lanrutcon/CatchTheWind#10]
![2016-08-20 3 19 32](https://cloud.githubusercontent.com/assets/17880706/17827405/0aa6a5a8-6685-11e6-8dd2-42a415d50c42.png)
... please help. This addon makes me want to subscribe again!

Accept, Decline and Thank_you buttons are in English which looks cool and is not a serious issue

**Comment by Lanrutcon** [comment]
The Quest Text should be working for foreign countries: https://github.com/Lanrutcon/CatchTheWind/commit/7042285af5a337337c78beff96ecf12f83715b98

The buttons will be translated in the future.
