### ISSUE TITLE
[Bug] Screenshot does not work while CTW is open

### ISSUE THREAD

**Issue by benoitheylens** [Lanrutcon/CatchTheWind#12]
Hi,

I tried to take a screenshot (with printscreen) to show a bug with loot distribution screen (overlapping of item tooltips), and it failed. Seems that everything but A and D keys and mousclics are disabled while CTW quest is open.

Any clue why ?

**Comment by Lanrutcon** [comment]
Hello and thanks for reporting.

Like you said, only some keys are doing actions. The rest doesn't do anything.
I'll add the PrintScreen key in the next couple of days.

Thanks for your suggestion.

**Comment by Lanrutcon** [comment]
Implemented in: https://github.com/Lanrutcon/CatchTheWind/commit/9dd84abba1f7e769b0f66a2dc74568c2f8b23f84
PrintScreen key could not be "picked up" by the addOn, so press F12 if you want to take a screenshot while the addOn is visible.
