### ISSUE TITLE
Reward tooltips are overlapped by overlay.

### ISSUE THREAD

**Issue by chevex** [Lanrutcon/CatchTheWind#13]
![world of warcraft 9_5_2016 3_50_22 pm](https://cloud.githubusercontent.com/assets/874394/18257425/b33458e8-7380-11e6-98aa-7c29b84beb5d.png)
![world of warcraft 9_5_2016 3_50_31 pm](https://cloud.githubusercontent.com/assets/874394/18257428/b853b2d8-7380-11e6-9a42-d5643d0efdf8.png)

You can see how the comparison tooltip on the right is cut off on the bottom and the other one is kind of hidden by the choose your reward overlay. Zooming in/out the camera does not affect it.

**Comment by benoitheylens** [comment]
I add that when you got a ring, with two slots you can equip, the second object overlap the first one.
Maybe you should "center-left" the reward to make space for two possible slot comparaison.

If I am not clear, please tell me.

**Comment by Lanrutcon** [comment]
Hello.

The main problem should be fixed in the latest version (v1.3.3).

@benoitheylens, I also fixed the screenshot problem. Could you take a screenshot of your problem?

**Comment by chevex** [comment]
I should mention I was unable to use in-game screenshot functionality for those screenshots. I had the Windows 10 Xbox app open and was able to use the Windows key + alt + print screen to take them.

**Comment by chevex** [comment]
Thanks for fixing the overlay :)

**Comment by benoitheylens** [comment]
I try to join a screenshot here :

![catchthewind1_3_3](https://cloud.githubusercontent.com/assets/21984111/18291830/92efee34-748a-11e6-8bce-2b6fd0726c5b.jpg)

(and you also have an example of some quest "double popping" with both classic and ctw display)

**Comment by chevex** [comment]
I can confirm that in a few instances you will see the normal quest window. It will be visible but not clickable since it's still behind the CTW overlay as expected. It doesn't break any functionality but does take you out of the otherwise seamless CTW dialogue experience.

One area you can reproduce this issue is when you are choosing your artifact weapon. Happened on my hunter and my warrior when getting the quest for my artifact weapons and it also happened on my friend's priest who I convinced to try the mod with me the day before yesterday.

**Comment by Lanrutcon** [comment]
Hello again.

Unfortunately, I'm using the "trial version" of World of Warcraft (max lvl20) to test/debug. So, currently I'm "slave" to users' reports.

Tomorrow, I'll fix an handful of bugs and add some suggestions. The "off-topic" bug (Blizzard QuestFrame visible) will be fixed as well.


To the "second-main-topic" (i.e. tooltips on top of each other). My first solution is to scale down the tooltips' size. I will also try to attach to a different point (currently, it's attached to TOPLEFT corner of RewardButton), if it works nicely, it won't be need to scale down.


Thanks for reporting and have a pleasant day.

**Comment by benoitheylens** [comment]
Hi there! 

I suggest you to copy your wow folder to another place without your cache and interface folders. So you will be able to launch wow with your main account without messing with your game configuration.  Unless you don't have a real paid subscription... If so ignore my message :D

**Comment by Lanrutcon** [comment]
Tooltips should no longer cause issues from now on. Also Blizzard UI won't appear anymore when the addon is visible.

Fixed in commit: https://github.com/Lanrutcon/CatchTheWind/commit/2c8c173089f88182d03eabcd014067bb0ab1a066

**Comment by benoitheylens** [comment]
Awesome! I'll test it tomorrow and I hope it will convince many guildmates to use it!
