### ISSUE TITLE
[Feature request] Sound !

### ISSUE THREAD

**Issue by benoitheylens** [Lanrutcon/CatchTheWind#15]
Why don't you add the option to add the old quest sound ?
You know, back in the days, in vanilla, when you took a quest, you had the text fading in like in ctw and a nice feather sound writing on a paper. I don't know, it felt so right then ... *want nostalrius back so badly*. ;)

**Comment by chevex** [comment]
That writing sound might actually be cool with the scrolling text. I'd have to hear it in action though since I don't remember it very well.

**Comment by benoitheylens** [comment]
http://www.wowhead.com/sound=3093/writequest

It was a combination,  a random sequence of these sounds.

**Comment by Lanrutcon** [comment]
Thanks for your suggestion and the sound-link.

Added in commit: https://github.com/Lanrutcon/CatchTheWind/commit/2c8c173089f88182d03eabcd014067bb0ab1a066

**Comment by chevex** [comment]
This addition is so awesome btw. I've been loving it.
