### ISSUE TITLE
[Feature request] CTRL+click to visualize and get a look on character

### ISSUE THREAD

**Issue by benoitheylens** [Lanrutcon/CatchTheWind#16]
A thing I like to do while questing is to preview the stuff I'll chose as a reword on my character.
Even if you do it by the default 'mog rendering or by rendering yourself a 3D character "naked" with the piece of stuff we get, it would be very nice to CTRL+click a reward and see how it looks on our character.

**Comment by chevex** [comment]
While I agree with this one I think it's a low priority unless it's really easy to fix. I'm not sure how difficult this change would be but it seems like it might not be a simple change.

You are able to hit F10 to hide the CTW overlay and see the normal quest window with the rewards in it. I've just been pressing F10 and then ctrl+clicking the rewards there. It's one of the more minor inconveniences sinces it's easily worked around. When there aren't more important updates to be made or this one is actually easier than I'm imagining then I think this change would be great.

**Comment by Lanrutcon** [comment]
Thanks for your suggestion.

Added in commit: https://github.com/Lanrutcon/CatchTheWind/commit/2c8c173089f88182d03eabcd014067bb0ab1a066
