### ISSUE TITLE
[Feature request] Prepare main lua for localization

### ISSUE THREAD

**Issue by benoitheylens** [Lanrutcon/CatchTheWind#20]
Hi there !

If you prepare me a main lua that point to sub-locale files, I can translate it to french for you.
I am not confortable enough with lua to write it on my own, I saw other addons using ace3 libs to do it.
You just have to change the "settext" so we can translate on a separate file.

No offense to you, by no mean, but here is a link that could help if you don't know what I am talking about :

http://wowwiki.wikia.com/wiki/Localizing_an_addon

**Comment by Lanrutcon** [comment]
Hello.

The new version is ready to get translations from other languages.

Inside the file _Localization.lua_, there are all the words and phrases that are being used by the addon. It should be fairly easy to read and understand, even if you are not "fluent" in Lua. There is an "example" for ptPT/ptBR, use it as a guide.

If you translate to **French**, please send back the translation. This way, all players that are using a french WoW client will have all words in french. Use https://gist.github.com/ to upload the file.
