### ISSUE TITLE
[bug] Lua error when comparing items (rings)

### ISSUE THREAD

**Issue by benoitheylens** [Lanrutcon/CatchTheWind#21]
```
7x CatchTheWind\Utils.lua:108: ShoppingTooltip2:SetPoint(): ShoppingTooltip1 is dependent on this
[C]:: in function 'SetPoint'
CatchTheWind\Utils.lua:108: in function 'CTW_GameTooltip_ShowCompareItem'
[string "*:OnEnter"]:12: in function <[string "*:OnEnter"]:1>
```

Also, when we have to compare rings, it shows only one ring to compare, not both rings.

**Comment by Lanrutcon** [comment]
Similar to: https://github.com/Lanrutcon/CatchTheWind/issues/17#issuecomment-246193868

Fixed in: https://github.com/Lanrutcon/CatchTheWind/commit/2c8c173089f88182d03eabcd014067bb0ab1a066

Thanks for reporting.
