### ISSUE TITLE
[Enhancement] Use system fonts (e.g. QuestFont_Large etc.) for fonts so that UIs which change system fonts affect the text fonts for quests

### ISSUE THREAD

**Issue by joev** [Lanrutcon/CatchTheWind#23]
Hi,

Love, love, love this addon. Thank you so much for vastly enhancing the questing experience for us. 

One thing I would love, is if you used system font sets instead of explicitly setting the font. The reason I ask is because those of us who use whole UI replacements (I personally use SuperVillain UI but there are many others such as ElvUI etc.) can have the text appear in the expected fonts.

See how cool it looks (in SVUI) here: 

http://imgur.com/a/N8Grz

I've been going through and modifying CTW to enable this locally for myself but there are two problems: 
1. I have to modify whenever you release a new version (not your problem of course :> but would be good to use standard fonts imho)
2. To allow the fonts to be modified dynamically you'd have to refactor so that the FontStrings are created not at addon-load but at time of display otherwise you'd have to add plenty of OptionalDeps to the toc (to make sure CTW loads later than them and picks up the relevant fonts)

**Comment by benoitheylens** [comment]
I support that. Or a way to select fonts in sharedmedia (but could be "dangerous", since It would break the "standalone" feature of your addon).

Here with "Black Chancery"

http://dl.dropboxusercontent.com/u/10459453/WoW/Divers/Fonts/BlackChancery.ttf

![catchthewind_1_5_custom_fonts](https://cloud.githubusercontent.com/assets/21984111/18606467/5f49d16a-7cb1-11e6-86ad-48a6206c7391.jpg)

**Comment by benoitheylens** [comment]
@Lanrutcon : 
Here is an example of what I thought for quest title. It uses the new UI for garrison and quests popup.

http://images.staticjw.com/wor/7327/new-trait-available.png

**Comment by benoitheylens** [comment]
![wowscrnshot_091816_215555](https://cloud.githubusercontent.com/assets/21984111/18651985/269b272c-7ecf-11e6-8b17-fcec3b3ca5dc.jpg)

Better example.

**Comment by benoitheylens** [comment]
No news :) ?

**Comment by Lanrutcon** [comment]
Hello.
These last weeks have been stressful for me and I barely had time to work.

I have returned today and already fixed this issue, so all addons that modify quest text fonts, CatchTheWind should use them as well.

About the quest title animation, I'm still thinking the best way to do it.

**Comment by Lanrutcon** [comment]
The addon should now use the others Addons font (STANDART_TEXT_FONT).
Also, the quest title has now a new animation.

https://github.com/Lanrutcon/CatchTheWind/commit/1c8ea791386e35a5c8a745d6f48abbb9fb8b1bfe
