### ISSUE TITLE
French (FR) Localisation [provided inside]

### ISSUE THREAD

**Issue by neskweek** [Lanrutcon/CatchTheWind#26]
Hello,
Here is a translation proposition for French : 

```
elseif(locale == "frFR" ) then
    L = {
        --QuestFrame
        ACCEPT = "Accepter",
        DECLINE = "Refuser",
        CHOOSE_YOUR_REWARD = "Choisir la récompense",
        CONTINUE = "Continuer",
        GOODBYE = "Au revoir",
        THANK_YOU = "Merci",


        --OptionsMenu
        CAMERA = "Caméra",
        QUEST = "Quête",
        CREDITS = "Crédits",


        --CameraOptions
        ENABLE_CAMERA_ZOOM = "Activer le zoom caméra",
        SAVE_YOUR_VIEW = "Sauver votre vue",
        CUSTOM_VIEW = "Vue personnalisée",

        --CameraTooltips
        ENABLE_CAMERA_ZOOM_TOOLTIP = "La caméra zoome +/- quand un PNJ a une quête dont il veut parler",
        SAVE_YOUR_VIEW_TOOLTIP = "Après avoir parler au PNJ, il dézoome pour restaurer votre vue.\n\nAttention: Cela désactive les mouvements caméra.\n Après la désactivation, tapez: /ctw fixCam.",
        CUSTOM_VIEW_TOOLTIP = "Créé une vue personnalisée pour l'interaction.\nD'abord, positionnez la caméra et ensuite activez cette option.",


        --QuestOptions
        SHOW_PREVIOUS_TEXT = "Voir le texte précédent",
        CHANGE_TEXT_SPEED = "Changer la vitesse du texte",
        ENABLE_QUEST_SOUND = "Activer le son",

        --QuestTooltips
        SHOW_PREVIOUS_TEXT_TOOLTIP = "Au passage du prochain paragraphe, le précédent sera affiché au dessus.",
        CHANGE_TEXT_SPEED_TOOLTIP = "Change la vitesse de défilement du texte de quête.",
        CHANGE_TEXT_SPEED_TOOLTIP2 = "Vitesse actuelle du texte: %g",
        ENABLE_QUEST_SOUND_TOOLTIP = "Quand le texte de quête s'anime, un son d'écriture est joué.",
    };
```

Thanks for this mod ;)
Best Regards
Neskweek

**Comment by benoitheylens** [comment]
Salut !

Merci pour ton boulot. Je te présente ma traduction, un peu plus "roleplay" et moins littérale par rapport à l'anglais, et plus parlante (l'anglais est parfois austère dans la description du fonctionnement de l'addon). Mais peut-être pourrions-nous mettre notre travail en commun ?

_Hi !

Thank you for your job. Hereby I show you my translation, a bit more roleplay and less litteral than the English version. English is sometimes rough on the edges when it comes to describe how the addon works. Maybe could we work together to deliver a better translation ?_

`------------------------------------------
-- frFR (Français)
------------------------------------------
if(locale == "frFR") then
	L = {
		--QuestFrame
		ACCEPT = "Accepter",
		DECLINE = "Refuser",
		CHOOSE_YOUR_REWARD = "Choisissez votre récompense",
		CONTINUE = "Continuer",
		GOODBYE = "Au revoir",
		THANK_YOU = "Merci",


		--OptionsMenu
		CAMERA = "Caméra",
		QUEST = "Quête",
		CREDITS = "Crédits",


		--CameraOptions
		ENABLE_CAMERA_ZOOM = "Activer la vue rapprochée",
		SAVE_YOUR_VIEW = "Sauvegarder la position de votre caméra",
		CUSTOM_VIEW = "Position de caméra personnalisée",
		
		--CameraTooltips
		ENABLE_CAMERA_ZOOM_TOOLTIP = "La caméra zoome en avant lorsqu'un PNJ vous présente une quête, puis zoome arrière.",
		SAVE_YOUR_VIEW_TOOLTIP = "Après avoir interagi avec un PNJ, reviens à votre position caméra.\n\nWarning: Ceci désactive la capacité de la caméra à suivre votre personnage.\nAprès avoir désactivé cette fonctionnalité, tapez: /ctw fixCam.",
		CUSTOM_VIEW_TOOLTIP = "Définissez une position personnalisée de caméra pour l'interaction avec les PNJ.\nD'abord, positionnez la caméra et ensuite activez cette fonctionnalité.",
		
		
		--QuestOptions
		SHOW_PREVIOUS_TEXT = "Afficher le dialogue précédent",
		CHANGE_TEXT_SPEED = "Changer la vitesse de défilement du texte",
		ENABLE_QUEST_SOUND = "Activer le son de plume lors de la narration",
		
		--QuestTooltips
		SHOW_PREVIOUS_TEXT_TOOLTIP = "Après avoir lu un dialogue et cliqué sur le bouton Continuer, le dialogue lu s'affichera au-dessus de l'écran.",
		CHANGE_TEXT_SPEED_TOOLTIP = "Change la vitesse de défilement du texte lors d'une interaction avec un PNJ de quête.",
		CHANGE_TEXT_SPEED_TOOLTIP2 = "Modificateur actuel de défilement textuel : %g",
		ENABLE_QUEST_SOUND_TOOLTIP = "Lorque le texte défile, un son de plume écrivant sur un parchemin est joué, ravivant de vieux souvenirs.",
	};

0
`

**Comment by neskweek** [comment]
Hello

The one proposed by benoitheylens is better ;)

Best Regards

**Comment by benoitheylens** [comment]
@neskweek Merci pour ton travail ! Ca prouve qu'on est tous motivés par cet addon ^_^ ! Vivement le retour de l'ActionCam !

**Comment by Lanrutcon** [comment]
Added in https://github.com/Lanrutcon/CatchTheWind/commit/1c8ea791386e35a5c8a745d6f48abbb9fb8b1bfe

Thank you both of you.
