### ISSUE TITLE
[Bug] Daily quest for raid token

### ISSUE THREAD

**Issue by benoitheylens** [Lanrutcon/CatchTheWind#27]
![wowscrnshot_092216_222737](https://cloud.githubusercontent.com/assets/21984111/18808411/173ca42c-8262-11e6-9982-c753db16b713.jpg)
![wowscrnshot_092216_222740](https://cloud.githubusercontent.com/assets/21984111/18808413/175b1f74-8262-11e6-85be-1baaade44c4b.jpg)

As shown on the screenshot, there is a bug when I use CTW with this quest. The warning for gold does not appear and the quest bugs, even if I press Escape and then click Ok, I don't get the token.

Any clue ?

**Comment by benoitheylens** [comment]
Any news ?

**Comment by Lanrutcon** [comment]
Fixed in https://github.com/Lanrutcon/CatchTheWind/commit/1c8ea791386e35a5c8a745d6f48abbb9fb8b1bfe
