### ISSUE TITLE
Options menu issues

### ISSUE THREAD

**Issue by thanwho** [Lanrutcon/CatchTheWind#29]
Lately I cannot open up the menu with /ctw and use it normally as I get this:

![image](https://user-images.githubusercontent.com/15257451/32937351-01580376-cb2d-11e7-9338-41b4032a43ab.png)

This is important because for new characters or those I haven't configured yet, the addon is useless, but it still functions normally for my characters that I've set it up on before it started bugging out like this. 

This is what bugsack outputs as the error:

1x CatchTheWind\GUIConfig.lua:8: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: in function `PlaySound'
CatchTheWind\GUIConfig.lua:8: in function `CatchTheWindConfigMenuButton_OnClick'
CatchTheWind\GUIConfig.lua:40: in function `CatchTheWindConfig_OnShow'
[string "*:OnShow"]:1: in function <[string "*:OnShow"]:1>
[C]: in function `Show'
CatchTheWind\Utils.lua:39: in function `frameFade'
CatchTheWind\CatchTheWind-1.7.1.lua:844: in function `?'
FrameXML\ChatFrame.lua:4512: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4180: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4216: in function <FrameXML\ChatFrame.lua:4212>
[C]: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = "igMainMenuOptionCheckBoxOn"

For some additional help, bugsack also catches this error whenever an option is selected or deselected in the /ctw menu:

8x CatchTheWind\GUIConfig.lua:21: Usage: PlaySound(soundKitID, optional["SFX","Music","Ambience", "Dialog" or "Master"], [forceNoDuplicates, runFinishCallback])
[C]: in function `PlaySound'
CatchTheWind\GUIConfig.lua:21: in function `CatchTheWindConfigCheckButton_OnClick'
[string "*:OnClick"]:1: in function <[string "*:OnClick"]:1>

Locals:
(*temporary) = "igMainMenuOptionCheckBoxOn"

**Comment by Lanrutcon** [comment]
Hello there.

This problem should be fixed in the next version (1.7.2), which will be released in the next couple of hours

Thank you and have a nice day.
