### ISSUE TITLE
[Feature Request] - Modifier Key for NPC interaction

### ISSUE THREAD

**Issue by ihithim** [Lanrutcon/CatchTheWind#7]
It would be good if there was an option to have a modifier key to block the opening of CatchTheWind when interacting with an NPC - i.e. when holding control and clicking on an NPC the default quest UI window appears - This might help with some unusual cases or just debugging

**Comment by Lanrutcon** [comment]
Implemented in: https://github.com/Lanrutcon/CatchTheWind/commit/6ae90697262c19c2c5db856c853cfd73bebf3ca4

Thanks for your suggestion.

_Closing_
